name: Upload Binaries and Docker Image

on:
  push:
    branches:
      - feat/rocksdb-v0.17.0

jobs:
  release-binaries:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version:
          - 1.18
        os: [ubuntu-20.04]
        arch: [amd64]

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ secrets.ROCKSDB_HOST }}
          privateKey: ${{ secrets.ROCKSDB_SSH_PRIVATE_KEY }}
          command: |
            # Install Golang
            sudo apt install golang-go
            # Rocksd has been initialized on the server manually
            # sudo echo 'export LD_LIBRARY_PATH=/usr/local/lib' >> $HOME/.bashrc (done manually)
            # build binary
            export LD_LIBRARY_PATH=/usr/local/lib
            git clone https://github.com/axelarnetwork/axelar-core.git
            cd axelar-core
            git checkout feat/rocksdb-v0.17.0
            make build
            mkdir -p ~/.axelar_testnet-2/bin 
            mv ./bin/axelard ~/.axelar_testnet-2/bin/axelard-v0.17.0
            chmod +x ~/.axelar_testnet-2/bin/axelard-v0.17.0
            cd  
            git clone https://github.com/axelarnetwork/axelarate-community.git
            cd axelarate-community
            # Create necessary folders and get config files
            ulimit -n 16384
            yes | ./scripts/setup-node.sh -n testnet-2 -a v0.17.0
            # That folder is missing
            mkdir -p ~/.axelar_testnet-2/data/snapshots/metadata.db
            # We need to update the DB backend in config.toml file
            sed -i 's/db_backend = "goleveldb"/db_backend = "rocksdb"/' ~/.axelar_testnet-2/config/config.toml 
            # Display config.toml file
            cat ~/.axelar_testnet-2/config/config.toml
            # Sync the node 
            ~/.axelar_testnet-2/bin/axelard start [moniker] --home ~/.axelar_testnet-2 >> ~/.axelar_testnet-2/logs/axelard.log 2>&1 &














